### ISSUE TITLE
List tab shows nothing

### ISSUE THREAD

**Issue by pawamoy** [mandeep/Mausoleum#3]
The list tab does not seem to work!

Maybe it's still under development?

I've clicked several time on the update button of course. Is there a debug mode so I can investigate further more?

![screenshot - 08172017 - 12 51 58 pm](https://user-images.githubusercontent.com/3999221/29409102-1334cae0-834b-11e7-9d5b-0addce796b87.png)

**Comment by mandeep** [comment]
Thanks for reporting this. Could you let me know which version of Tomb you are using?

**Comment by pawamoy** [comment]
Sure, I have tomb version 2.3.
Also just tried with 2.4 and same issue.

**Comment by mandeep** [comment]
Thanks for letting me know. 2.3 broke a lot of things with Mausoleum and I assume they weren't fixed with 2.4. As of right now 2.2 will be your best bet. I'll open an issue on the Tomb issue tracker once I identify all of the breaking changes.

**Comment by mandeep** [comment]
@Pawamoy I decided to dig into this and I'm unable to replicate this issue with Tomb 2.4. Are you still experiencing this issue?

**Comment by pawamoy** [comment]
@mandeep I just upgraded to mausoleum 0.8.5 and can confirm that the list tab is still empty!
EDIT: also tried with most recent Tomb 2.5 and I still experience the issue.

**Comment by mandeep** [comment]
@Pawamoy I'm unable to replicate this issue in Tomb 2.5 as well, but I've pushed a possible fix in 0.8.6 that may help.

**Comment by pawamoy** [comment]
Ah yes! It's working now :) Thank you, feel free to close :)

**Comment by mandeep** [comment]
Awesome! Thanks for your patience and for working with me on this. :smile:
